export const INCRESDE_WORD_SEARCH_COUNT = 'INCRESDE_WORD_SEARCH_COUNT';
export const REQUEST_FETCHING_WORD = 'REQUEST_FETCHING_WORD';
export const SUCCESS_FETCHING_WORD = 'SUCCESS_FETCHING_WORD'
export const REJECT_FETCHING_WORD = 'REJECT_FETCHING_WORD';
